name: Docker build

on: [push]

env:
  PYTHON_VERSION: "3.10"
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "nightcrawler-pipeline"

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Building container image"
    #needs: [test-python,test-node]
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install poetry
        run: |
          pip install poetry==1.8.3

      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: 'smc40/nightcrawler-library'
          ssh-key: ${{ secrets.NC_LIBRARY_PULLER_KEY }}
          path: nightcrawler-library
          ref: 0.7.1

      - name: Use local directory libnightcrawler
        run: |
          poetry remove libnightcrawler --lock
          poetry add ./nightcrawler-library --lock

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

